apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: w711h63t6-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:e90140086ab9dfd9f6046e43f1a2e0e44d6c54e0@sha256:159e32c408e0e059f9ea47fe58b0683627a1d46ddd4341660ac39ac55dc12a33
          name: container-image
